In [36]:
import torch
from IPython import display
from d2l import torch as d2l

In [37]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [38]:
num_inputs = 784
num_outputs = 10

W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_inputs, requires_grad=True)

In [39]:
X = torch.arange(6.0).reshape(2, 3)
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[3., 5., 7.]]),
 tensor([[ 3.],
         [12.]]))

In [40]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition

In [41]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X_prob, X_prob.sum(1, keepdim=True)

(tensor([[0.2920, 0.0487, 0.0674, 0.0842, 0.5077],
         [0.3389, 0.1987, 0.0419, 0.0190, 0.4014]]),
 tensor([[1.],
         [1.]]))

In [42]:
# X = torch.randn(5, 4)
# W = torch.randn(4, 3, requires_grad=True)
# b = torch.randn(3, requires_grad=True)



In [43]:
def net(X):
    Y = torch.matmul(X.reshape((-1, W.shape[0])), W) + b
    return softmax(Y)

In [44]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]


tensor([0.1000, 0.5000])

In [45]:
y_hat.shape, len(y_hat.shape), y_hat.shape[1]

(torch.Size([2, 3]), 2, 3)

In [46]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y])

cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])

In [47]:
def accuracy(y_hat, y):
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    cmp = cmp.sum()
    return cmp 

In [48]:
accuracy(y_hat, y)

tensor(1)

In [49]:
class Accumulator:
    def __init__(self, n):
        self.data = [0.0] * n
    
    def add(self, *args):
        self.data = [a + float(b) for a, b in zip(self.data, args)]
    
    def reset(self):
        self.data = [0.0] * len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [ ]:
def evaluate_accuracy(net, data_iter):
    if isinstance(net, torch.nn.Module):
        net.eval()
    metric = Accumulator(2)
    with torch.no_grad():
        for X, y in data_iter:
            print(X.shape, y.shape)
            metric.add(accuracy(net(X), y), y.numel())
    return metric[0] / metric[1]
    

In [51]:
evaluate_accuracy(net, test_iter)

RuntimeError: The size of tensor a (10) must match the size of tensor b (784) at non-singleton dimension 1

In [ ]:
print()